name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  coveralls:
    needs: test-multi-python
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true

  test-multi-os:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - uses: actions/cache@v3
      with:
        key: v0-${{ runner.os }}-pip-test-${{ hashFiles('setup.py') }}
        path: ~/.cache/pip
        restore-keys: |
          v0-${{ runner.os }}-pip-test-
          v0-${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]

    - name: Test with pytest
      run: pytest

  test-multi-python:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/cache@v3
      with:
        key: v0-${{ runner.os }}-pip-test-${{ hashFiles('setup.py') }}
        path: ~/.cache/pip
        restore-keys: |
          v0-${{ runner.os }}-pip-test-
          v0-${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
        pip install coveralls

    - name: Test with pytest
      run: coverage run --source prsw --module pytest

    - name: Generate Coveralls LCOV report
      run: coverage lcov

    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: run-${{ matrix.python-version }}
        path-to-lcov: ./coverage.lcov
        parallel: true

    - name: Check coverage
      run: coverage report -m --fail-under=100
